### ISSUE TITLE
ReSvnRepositoryCompatibility.Subversion19 creates repo with format 8 instead of 7

### ISSUE THREAD

**Issue by jtothe4n** [AmpScm/SharpSvn#48]
When creating a repository it will create it with format 8 as default.
That would not be an issue if it could then at least checkout its own created repository, but it will throw
an exception with "[Expected FS format between ‘1’ and ‘7’; found format ‘8’].
Also you cant checkout that repo with e.g. tortoise SVN, same error.

I then tried using RepositoryCompatibility = SvnRepositoryCompatibility.Subversion19 which should create the repo with format 7.
But it does not. [as seen here](https://github.com/AmpScm/SharpSvn/blob/0f62bb186a2f6bae6ff434419953b773cad77e0f/src/SharpSvn/ReposCommands/CreateRepository.cpp#L118) it is the same as the default, which seems to be 8?

using SvnRepositoryCompatibility.Subversion18 instead creates the repository correctly with format 6. Which I'm using now as workaround

**Comment by rhuijben** [comment]
I will integrate a patch in the next release, but since Subversion 1.10 are all out of support these days I don't see this as a high priority issue.

I would recommend passing the lower flag for that version, but you already found that workaround.

In general I would recommend using a proper Subversion server, and just using SharpSvn at the client with a proper security boundary, for obvious reasons. But this should work for testing scenario's anyway.

**Comment by rhuijben** [comment]
Patch is applied on the development branch, and if needed you can pick up new binaries from the GitHub action

**Comment by jtothe4n** [comment]
Much appreciated, thanks!
